/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2023-12-16 22:04:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Models.Equipe;
import Models.Dev;
import Models.Technologie;
import Models.Projet;
import Models.Client;
import Models.Methodologie;
import Models.Chef;
import java.util.List;

public final class edit_002dprojet_002dchef_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Models.Chef");
    _jspx_imports_classes.add("Models.Projet");
    _jspx_imports_classes.add("Models.Dev");
    _jspx_imports_classes.add("Models.Methodologie");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Models.Client");
    _jspx_imports_classes.add("Models.Equipe");
    _jspx_imports_classes.add("Models.Technologie");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Edit Project Chef</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 Projet project = (Projet) request.getAttribute("Projet");
List<Methodologie> methodologies = (List<Methodologie>) request.getAttribute("Methods");
List<Technologie> Technologies = (List<Technologie>) request.getAttribute("technologies");
List<Integer> projetTechsIds = (List<Integer>) request.getAttribute("projetTechsIds");
List<Dev> devs=(List<Dev>) request.getAttribute("Devs");
Boolean isDevsVisible =(Boolean) request.getAttribute("isDevsVisible");
Boolean isDateReunionVisible =(Boolean) request.getAttribute("isDateReunionVisible");
Equipe equipe = (Equipe) request.getAttribute("equipe");


Chef chef=(Chef) request.getAttribute("chef");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- component -->\r\n");
if(project !=null){ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"min-h-screen p-6 bg-gray-100 flex items-center justify-center\">\r\n");
      out.write("<form action=\"EditProjectChef\" method=\"post\">\r\n");
      out.write("  <div class=\"container max-w-screen-lg mx-auto\">\r\n");
      out.write("    <div>\r\n");
      out.write("      <h2 class=\"font-semibold text-xl text-gray-600\">page de modification du projet pour le chef</h2>\r\n");
      out.write("      <p class=\"text-gray-500 mb-6\">Form is mobile responsive. Give it a try.</p>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"bg-white rounded shadow-lg p-4 px-4 md:p-8 mb-6\">\r\n");
      out.write("        <div class=\"grid gap-4 gap-y-2 text-sm grid-cols-1 lg:grid-cols-3\">\r\n");
      out.write("          <div class=\"text-gray-600\">\r\n");
      out.write("            <p class=\"font-medium text-lg\">Détails du projet</p>\r\n");
      out.write("          </div>\r\n");
      out.write("			<input type=\"hidden\" name=\"projectId\" value=\"");
      out.print(project.getId() );
      out.write("\" >\r\n");
      out.write("			<input type=\"hidden\" name=\"idChef\" value=\"");
      out.print(chef.getId() );
      out.write("\" >\r\n");
      out.write("          <div class=\"lg:col-span-2\">\r\n");
      out.write("            <div class=\"grid gap-4 gap-y-2 text-sm grid-cols-1 md:grid-cols-5\">\r\n");
      out.write("              <div class=\"md:col-span-5\">\r\n");
      out.write("                <label for=\"full_name\">Nom du projet</label>\r\n");
      out.write("                <input type=\"text\" name=\"nomProject\" id=\"full_name\" value=\"");
      out.print(project.getNom() );
      out.write("\" class=\"h-10 border mt-1 rounded px-4 w-full bg-gray-50\" value=\"\" disabled=\"disabled\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"md:col-span-5\">\r\n");
      out.write("                <label for=\"description\" >Description du projet</label>\r\n");
      out.write("                <input type=\"text\" name=\"projectDescription\" value=\"");
      out.print(project.getDescription() );
      out.write("\" class=\"h-10 border mt-1 rounded px-4 w-full bg-gray-50\" value=\"test\" disabled=\"disabled\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"md:col-span-3\">\r\n");
      out.write("                <label for=\"date_demarrage\">Date de démarrage</label>\r\n");
      out.write("                <input type=\"date\" name=\"dateDemarrage\" value=\"");
      out.print(project.getDateDemarage() );
      out.write("\" id=\"address\" class=\"h-10 border mt-1 rounded px-4 w-full bg-gray-50\" disabled=\"disabled\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"md:col-span-2\">\r\n");
      out.write("                <label for=\"date_livraison\">Date de livraison</label>\r\n");
      out.write("                <input type=\"date\" name=\"dateLivraison\" value=\"");
      out.print(project.getDateLivraison() );
      out.write("\" id=\"date_livraison\" class=\"h-10 border mt-1 rounded px-4 w-full bg-gray-50\" disabled=\"disabled\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("	\r\n");
      out.write("              \r\n");
      out.write("         \r\n");
      out.write("             <div class=\"md:col-span-2\">                \r\n");
      out.write("    <label for=\"methodologies\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Choisir une methodologie</label>\r\n");
      out.write("    <select id=\"methodologies\" name=\"selectedMethodology\" class=\"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500\">\r\n");
      out.write("        ");
 for (Methodologie meth : methodologies) { 
      out.write("\r\n");
      out.write("            <option ");
if(project.getMethodologie()!=null && project.getMethodologie().getNom().equals(meth.getNom())){ 
      out.write(" selected ");
} 
      out.write(" value=\"");
      out.print( meth.getId() );
      out.write('"');
      out.write('>');
      out.print( meth.getNom() );
      out.write("</option>\r\n");
      out.write("            \r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </select>                                \r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("<div class=\"md:col-span-2\">                \r\n");
      out.write("    <label class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Choisir une ou des technologies</label>\r\n");
      out.write("    <div class=\"grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4\">\r\n");
      out.write("    ");
 for (Technologie tech : Technologies) { 
      out.write("\r\n");
      out.write("        <label class=\"flex items-center\">\r\n");
      out.write("            <input type=\"checkbox\" name=\"selectedTechnologies\" value=\"");
      out.print( tech.getId() );
      out.write("\" class=\"rounded border-gray-300 text-blue-500 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50\"\r\n");
      out.write("                ");
 
                for(Integer idTech : projetTechsIds){
                	if(idTech.equals(tech.getId())){
                
         
                        
                    
                
      out.write(" checked=\"checked\"");
 }} 
      out.write("\r\n");
      out.write("            />\r\n");
      out.write("            <span class=\"ml-2\">");
      out.print( tech.getNom() );
      out.write("</span>\r\n");
      out.write("        </label>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                               \r\n");
      out.write("</div>\r\n");
      out.write("                               \r\n");
      out.write("              </div> \r\n");
      out.write("      			\r\n");
      out.write("              <div class=\"md:col-span-5 text-right\">\r\n");
      out.write("                <div class=\"inline-flex items-end\">\r\n");
      out.write("				<!-- infos client -->\r\n");
      out.write("                  <input type=\"submit\" value=\"Submit\" class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("  </form>     \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("     ");
 if (isDevsVisible != null && isDevsVisible && devs != null && !devs.isEmpty()) { 
      out.write("\r\n");
      out.write("    <!-- devs shown start here -->\r\n");
      out.write("   <form action=\"creerEquipeServlet\" method=\"post\" id=\"secondForm\">\r\n");
      out.write("    <div class=\"bg-white rounded shadow-lg p-4 px-4 md:p-8 mb-6\">\r\n");
      out.write("        <div class=\"gap-4 gap-y-2 text-sm grid-cols-1 lg:grid-cols-3\">\r\n");
      out.write("            <div class=\"text-gray-600\">\r\n");
      out.write("                <p class=\"font-medium text-lg\">Liste des développeurs convenables</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"hidden\" name=\"idproject\" value=\"");
      out.print(project.getId() );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"idChef\" value=\"");
      out.print(chef.getId() );
      out.write("\" >\r\n");
      out.write("            ");
 for (Dev dev : devs) { 
      out.write("\r\n");
      out.write("                ");
 
                boolean hasMatchingTech = false;
                for (Technologie tech : dev.getTechnologies()) {
                    if (projetTechsIds.contains(tech.getId())) {
                        hasMatchingTech = true;
                        break;
                    }
                }
                if (hasMatchingTech) { 
      out.write("\r\n");
      out.write("                    <div class=\"flex items-center justify-between\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p>");
      out.print( dev.getUsername() );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"flex text-gray-400\" >\r\n");
      out.write("                            <p>Technologies:</p>\r\n");
      out.write("                            ");
 for (Technologie tech : dev.getTechnologies()) { 
      out.write("\r\n");
      out.write("                                <p>");
      out.print( tech.getNom() );
      out.write("</p>\r\n");
      out.write("                               \r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label class=\"inline-flex items-center\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"selectedDevs\" value=\"");
      out.print(dev.getId() );
      out.write("\" class=\"form-checkbox\">\r\n");
      out.write("                            <span class=\"ml-2\">Select</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <div class=\"md:col-span-5 text-right\">\r\n");
      out.write("                <div class=\"inline-flex items-end\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Créer Equipe\" class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\" onclick=\"submitForms(event)\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- devs shown end here -->\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     ");
 if (isDateReunionVisible != null && isDateReunionVisible) { 
      out.write("\r\n");
      out.write("    <!-- devs shown start here -->\r\n");
      out.write("    <form action=\"ajouterDateReunionServlet\" method=\"post\" id=\"thirdForm\">\r\n");
      out.write("        <div class=\"bg-white rounded shadow-lg p-4 px-4 md:p-8 mb-6\">\r\n");
      out.write("            <div class=\"gap-4 gap-y-2 text-sm grid-cols-1 lg:grid-cols-3\">\r\n");
      out.write("                <div class=\"text-gray-600\">\r\n");
      out.write("                    <p class=\"font-medium text-lg\">Choisir une date de reunion</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"hidden\" name=\"idproject\" value=\"");
      out.print(project.getId() );
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"idChef\" value=\"");
      out.print(chef.getId() );
      out.write("\">\r\n");
      out.write("                \r\n");
      out.write("                <input type=\"date\" name=\"dateReunion\" id=\"address\" class=\"h-10 border mt-1 rounded px-4 w-full bg-gray-50\" required />\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"md:col-span-5 text-right\">\r\n");
      out.write("                    <div class=\"inline-flex items-end\">\r\n");
      out.write("                        <input type=\"submit\" value=\"Enregistrer Projet\" class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\" onclick=\"submitForms(event)\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <!-- devs shown end here -->\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <form action=\"EditProjectChef\" method=\"post\" >\r\n");
      out.write(" \r\n");
      out.write(" <h1>devs are shown</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 }else{ 
      out.write("\r\n");
      out.write("<h1>Project est null</h1>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function submitForms(event) {\r\n");
      out.write("    event.preventDefault(); // Prevent the default form submission\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('secondForm').submit(); // Submit second form\r\n");
      out.write("    document.getElementById('thirdForm').submit(); // Submit third form\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
