/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2023-12-16 14:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Models.User;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Models.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 User user = (User) session.getAttribute("user"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- component -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("    /* Estilos para el señalador de posición (border-left) */\r\n");
      out.write("    .sidebar li:hover a::before {\r\n");
      out.write("      content: \"\";\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      width: 4px;\r\n");
      out.write("      background: linear-gradient(to bottom, #00FFFF, #008080); /* Gradiente cyan */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Estilos para cambiar el color del ícono y el texto a blanco al pasar el cursor */\r\n");
      out.write("    .sidebar li:hover a i,\r\n");
      out.write("    .sidebar li:hover a span {\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("  <!-- Sidebar -->\r\n");
      out.write("  <div class=\"fixed flex flex-col top-14 left-0 w-14 hover:w-64 md:w-64 bg-black h-full  transition-all duration-300 border-none z-10 sidebar\">\r\n");
      out.write("    <div class=\"overflow-y-auto overflow-x-hidden flex flex-col justify-between flex-grow\">\r\n");
      out.write("      <ul class=\"flex flex-col py-4 space-y-1\">\r\n");
      out.write("      ");
 if(user != null && user.getRole() == 1){ 
      out.write("\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"directorAccueil\" class=\"relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-black border-l-4 border-transparent\">\r\n");
      out.write("            <!-- Icono Home de Font Awesome -->\r\n");
      out.write("            <span class=\"inline-flex justify-center items-center ml-4\">\r\n");
      out.write("              <i class=\"fas fa-home\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("                        \r\n");
      out.write("            <span class=\"ml-2 text-sm text-white tracking-wide truncate\">Accueil</span>\r\n");
      out.write("            \r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        ");
 if(user != null && user.getRole() == 1){ 
      out.write("\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"ajouterProject\" class=\"relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent\">\r\n");
      out.write("            <!-- Icono Check Circle de Font Awesome -->\r\n");
      out.write("            <span class=\"inline-flex justify-center items-center ml-4\">\r\n");
      out.write("              <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"ml-2 text-sm text-white tracking-wide truncate\">Ajouter projet</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        ");
 if(user != null && user.getRole() == 1){ 
      out.write("\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"ajouterChef\" class=\"relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent\">\r\n");
      out.write("            <!-- Icono Users de Font Awesome -->\r\n");
      out.write("            <span class=\"inline-flex justify-center items-center ml-4\">\r\n");
      out.write("              <i class=\"fas fa-users\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"ml-2 text-sm text-white tracking-wide truncate\">Ajouter Chef</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        ");
 if(user != null && user.getRole() == 1){ 
      out.write("\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"ajouterMethodologie\" class=\"relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent\">\r\n");
      out.write("            <!-- Icono Store de Font Awesome -->\r\n");
      out.write("            <span class=\"inline-flex justify-center items-center ml-4\">\r\n");
      out.write("              <i class=\"fas fa-store\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"ml-2 text-sm text-white tracking-wide truncate\">Ajouter Methodologie</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"ajouterTechnologie\" class=\"relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent\">\r\n");
      out.write("            <!-- Icono Store de Font Awesome -->\r\n");
      out.write("            <span class=\"inline-flex justify-center items-center ml-4\">\r\n");
      out.write("              <i class=\"fas fa-store\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"ml-2 text-sm text-white tracking-wide truncate\">Ajouter Technologie</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"disconnect\" class=\"relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent\">\r\n");
      out.write("            <!-- Icono Sign Out de Font Awesome -->\r\n");
      out.write("            <span class=\"inline-flex justify-center items-center ml-4\">\r\n");
      out.write("              <i class=\"fas fa-sign-out-alt\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"ml-2 text-sm text-white tracking-wide truncate\">Log out</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <p class=\"mb-14 px-5 py-3 hidden md:block text-center text-xs\">Copyright @2021</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- ./Sidebar -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
